# 窗口大小设置(立绘默认自适应窗口大小)
window_width: 600
window_height: 800
always_on_top: true # 设置窗口始终保持顶置

# 立绘设置
tachie_path: "./tachie/Murasame/" # 立绘文件夹路径
default_tachie: "正常" # 默认立绘
opening_tachie: "高兴" # 开场时临时展现的表情
tachie_suffix: "png" # 立绘图片格式(后缀名)

# 对话框设置
dialog_label: "LaIN 绫" # 对话框标签名称(可作为人物名称)
dialog_opacity: 0.8 # 对话框透明度设置 (0.0-1.0]

# letta框架的agent_id设置
agent_id: "agent-33418f62-6ec6-4263-8e92-147b27acdb87"

# vits语音生成设置
vits_api_url: "http://127.0.0.1:23456/voice/vits" # vits模型API路径 (默认接口一般不用修改)
vits_speaker_id: "4" # 采用的vits模型
vits_clean_text: true # 是否开启文本清洗 (去除难以发音的部分, 例如网页链接等)

# 语音识别设置
vad_mode: 2 # vad人声检测参数
model_name: "small" # whisper模型名称, 可选: tiny, base, small, medium, large, large-v3, large-v3-turbo
initial_prompt: "以下是提交给智能助手Lin的普通话为主的语音输入。" # whisper初始prompt, 可以优化语音识别效果
max_silence_duration: 1.8 # 持续静音max_silence_duration时间后自动停止录音并结束语音识别
