# 窗口大小设置 (立绘默认自适应窗口大小)
window_width: 600
window_height: 800
window_always_on_top: true # 设置窗口始终保持顶置

# 显示角色模式选择 (tachie or live2d)
character_display_mode: "live2d" # 可选项: [tachie|live2d]

# live2d
live2d_model_path: "./live2d/MuraSame/Murasame.model3.json"
live2d_lipSyncN: 4.3
# 请注意: 模型动作和表情的名称不能相同, 否则默认播放同名动作; 对于prompt可以统一写入emotion里交给LLM自行判断
live2d_motion_list: # live2d模型的动作清单 (更换模型需自行配置此处)
  [
    "Idle",
    "自豪地显摆",
    "好奇地探身",
    "高兴wink",
    "害羞地认同",
    "温柔wink",
    "害羞地偷瞄",
    "严肃地否认或拒绝",
    "阴郁地躲闪",
    "火冒三丈",
    "娇媚地靠近",
    "温柔地否认或拒绝",
  ]
live2d_expression_list: # live2d模型的表情清单 (更换模型需自行配置此处)
  [
    "正常脸",
    "微笑脸",
    "悲伤脸",
    "阴沉脸",
    "生气脸",
    "暴怒脸",
    "害羞脸",
    "羞愧脸",
  ]
live2d_default_expression: "正常脸" # live2d的默认表情
live2d_default_motion: "Idle" # live2d的默认动作
live2d_opening_expression: "害羞脸" # live2d的开场表情
live2d_opening_motion: "高兴wink" # live2d的开场动画

# 立绘(tachie)设置
tachie_path: "./tachie/Murasame/" # 立绘文件夹路径
tachie_default: "微笑" # 默认立绘
tachie_opening: "高兴" # 开场时临时展现的表情
tachie_suffix: "png" # 立绘图片格式 (后缀名)

# 对话框设置
dialog_label: "LaIN 绫" # 对话框标签名称 (可作为人物名称)
dialog_opacity: 0.8 # 对话框透明度设置 (0.0-1.0]

# letta框架的agent_id设置
letta_agent_id: "agent-6300306b-2e9e-477b-8d2a-add2120a7e39" # 填入你自己的agent_id, 详情参考letta文档: https://docs.letta.com/quickstart
letta_server_ip: "localhost" # letta服务部署的地址 (默认本地地址, 可自行选配远程服务)

# vits语音生成设置
vits_api_url: "http://127.0.0.1:23456/voice/vits" # vits模型API路径 (默认本地接口, 可自行选配远程服务)
vits_speaker_id: "4" # 采用的vits模型
vits_clean_text: true # 是否开启文本清洗 (去除难以发音的部分, 例如网页链接等)

# 语音识别设置
asr_vad_mode: 2 # vad人声检测参数
asr_webrtc_aec: false # 是否开启回声消除功能 (undo, 此项不可修改, 目前未实现)
asr_auto_send_silence_time: 1.8 # 持续静音asr_auto_send_silence_time时间后自动发送 (设置为-1则不自动发送)

# 声纹检测
vpr_match_only: ["tor"] # 对特定群体声纹开启语音识别 (需要关闭可以将List留空或填None, 关闭后匹配所有用户-->会导致无法打断语音, 因为还没实现回声消除XD)
vpr_db_dir: "voice_print_db" # 声纹数据库文件夹路径 (相对路径, 会自动创建)
vpr_model: "damo/speech_campplus_sv_zh-cn_16k-common" # 使用的声纹识别模型路径 (不用修改, 会自动下载)
vpr_similarity_threshold: 0.7 # 认可声纹匹配的精确度阈值
